
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
from cffi.setuptools_ext import execfile


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Toplevel, Menu

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("AssetsAnalyse")

# ==================================== enabling high DPI for windows ====================================
try:
    from ctypes import windll

    windll.shcore.SetProcessDpiAwareness(1)
except:
    pass
# ==================================== ACTIONS (functions) to RUN ===================================================

def donothing():
    x = 0

def switch_to_MainPage():
    #window.destroy()
    #exec(open('MainPage.py').read())
    x = 0

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1513x1075")
window.configure(bg = "#3A7FF6")

#================================  Menu Bar
menubar = Menu(window)
filemenu = Menu(menubar, tearoff=0)
filemenu.add_command(label="Tshoot", command=switch_to_MainPage())
filemenu.add_command(label="Analyse", command=donothing())
filemenu.add_separator()
filemenu.add_command(label="Exit", command=window.quit)
menubar.add_cascade(label="Mode", menu=filemenu)

helpmenu = Menu(menubar, tearoff=0)
helpmenu.add_command(label="Help Index", command=donothing)
helpmenu.add_command(label="About...", command=donothing)
menubar.add_cascade(label="Help", menu=helpmenu)

window.config(menu=menubar)

###########################

canvas = Canvas(
    window,
    bg = "#3A7FF6",
    height = 1075,
    width = 1513,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    433.0,
    0.0,
    1513.0,
    1075.0,
    fill="#FCFCFC",
    outline="")

canvas.create_text(
    24.0,
    11.0,
    anchor="nw",
    text="xShoot Platform",
    fill="#FFFFFF",
    font=("Arsenal Regular", 45 * -1)
)

canvas.create_text(
    150.0,
    96.0,
    anchor="nw",
    text="Analysis",
    fill="#FFFFFF",
    font=("Andika", 24 * -1)
)

canvas.create_text(
    20.0,
    149.0,
    anchor="nw",
    text="Select Files to Analyse Location",
    fill="#FFFFFF",
    font=("Andika", 15 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=302.0,
    y=149.0,
    width=31.704421997070312,
    height=26.62939453125
)

canvas.create_text(
    18.0,
    201.0,
    anchor="nw",
    text="Select an Analysis\n",
    fill="#FFFFFF",
    font=("Andika", 15 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    313.5,
    213.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#F1F5FF",
    highlightthickness=0
)
entry_1.place(
    x=264.0,
    y=201.0,
    width=99.0,
    height=23.0
)

canvas.create_rectangle(
    16.0,
    285.0,
    453.00006103515625,
    285.9732666015625,
    fill="#000000",
    outline="")

canvas.create_text(
    101.0,
    897.0,
    anchor="nw",
    text="Cloud Analysis DB",
    fill="#FFFFFF",
    font=("Andika", 24 * -1)
)

canvas.create_text(
    98.0,
    303.0,
    anchor="nw",
    text="Share with Fortinet",
    fill="#FFFFFF",
    font=("Andika", 24 * -1)
)

canvas.create_text(
    18.0,
    962.0,
    anchor="nw",
    text="Server",
    fill="#FFFFFF",
    font=("Andika", 15 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    156.5,
    974.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#F1F5FF",
    highlightthickness=0
)
entry_2.place(
    x=101.5,
    y=964.0,
    width=110.0,
    height=19.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=258.0,
    y=962.0,
    width=145.0,
    height=23.0
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    1413.0,
    25.0,
    image=image_image_1
)

canvas.create_text(
    675.0,
    48.0,
    anchor="nw",
    text="Issues",
    fill="#505485",
    font=("Andika", 20 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    706.5,
    524.0,
    image=entry_image_3
)
entry_3 = Text(
    bd=0,
    bg="#F1F5FF",
    highlightthickness=0
)
entry_3.place(
    x=471.0,
    y=86.0,
    width=471.0,
    height=874.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=484.0,
    y=1000.0,
    width=173.0,
    height=46.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=739.0,
    y=1002.0,
    width=172.0,
    height=44.0
)

canvas.create_rectangle(
    12.0,
    863.0,
    433.0,
    864.0,
    fill="#000000",
    outline="")

canvas.create_text(
    1150.0,
    48.0,
    anchor="nw",
    text="Analysis",
    fill="#505485",
    font=("Andika", 20 * -1)
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    1229.0,
    524.0,
    image=entry_image_4
)
entry_4 = Text(
    bd=0,
    bg="#F1F5FF",
    highlightthickness=0
)
entry_4.place(
    x=992.0,
    y=86.0,
    width=474.0,
    height=874.0
)

canvas.create_text(
    1006.0,
    1010.0,
    anchor="nw",
    text="v1.0   April 2022      https://github.com/abdessamad-elamrani/xshoot\n                             elamrani.abdessamad@gmail.com",
    fill="#274DD3",
    font=("Roboto Bold", 14 * -1)
)

canvas.create_text(
    20.0,
    381.0,
    anchor="nw",
    text="Select Files to Share Location",
    fill="#FFFFFF",
    font=("Andika", 15 * -1)
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=302.0,
    y=381.0,
    width=31.704421997070312,
    height=26.62933349609375
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    313.5,
    445.5,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#F1F5FF",
    highlightthickness=0
)
entry_5.place(
    x=264.0,
    y=433.0,
    width=99.0,
    height=23.0
)

canvas.create_text(
    18.0,
    433.0,
    anchor="nw",
    text="Select Case Number",
    fill="#FFFFFF",
    font=("Andika", 15 * -1)
)
window.resizable(False, False)
window.mainloop()
